spring.application.name=auth
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=springuser
spring.datasource.password=springpass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.flyway.user=springuser
spring.flyway.password=springpass
spring.flyway.url=jdbc:postgresql://localhost:5432/auth_db
spring.flyway.locations=classpath:db/migration
